# Generated by Django 5.0.1 on 2024-02-11 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=200)),
                ('direction', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=200)),
                ('img', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('slot_number', models.IntegerField()),
                ('bici', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='stations.bicis')),
                ('stations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='stations.stations')),
            ],
        ),
    ]
